version: 0.0

os: linux

files:
  - source: /
    destination: /home/ubuntu/wedevelop-site-mailer

hooks:
  BeforeInstall:
    - location: ./codedeploy-scripts/cleanup-destination-dir.sh
  AfterInstall:
    - location: ./codedeploy-scripts/set-permissions.sh
      runas: root
    - location: ./codedeploy-scripts/install-dependencies.sh
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy-scripts/app-stop.sh
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy-scripts/app-start.sh
      runas: ubuntu
